### ISSUE TITLE
Can you share chinese coNLL files?

### ISSUE THREAD

**Issue by Ramlinbird** [ontonotes/conll-formatted-ontonotes-5.0#4]
I can't find any resource except the origin ontonotes 5.0 free data at LDC which I don't have permission to access. If you have the chinese coNLL files or the origin data, I would be obliged if you could share it with me. Thanks again.

**Comment by maziyarpanahi** [comment]
The script does it actually for English, Arabic and Chinese:
![image](https://user-images.githubusercontent.com/5762953/60800079-cbdc4700-a174-11e9-832d-4e0e00611e12.png)
